#! bin/bash
cd ~/WEEK2_DAY3_EXERCISE
mkdir GITHUB_TEST
mkdir -p ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST{1_ANNOTATION, 2_ALPHABET, 3_NUMBERS}
mkdir -p ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/1_ANNOTATION{DATA, CODE, RESULTS}
mkdir -p ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/2_ALPHABET{DATA, CODE, RESULTS}
mkdir -p ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/3_NUMBERS{DATA, CODE, RESULTS}
