#! bin/bash
cd ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/2_ALPHABET
ln ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/1_ANNOTATION/DATA/*.* ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/2_ALPHABET/RESULTS
echo "for letter in {a..z} ; do
  echo $letter
done" > ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/1_ANNOTATION/RESULTS/initial_file.txt
