#! bin/bash
cd ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/2_ALPHABET
ln ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/1_ANNOTATION/RESULTS*.* ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/2_ALPHABET/DATA
echo "for letter in {a..z} ; do
  echo $letter
done" > ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/1_ANNOTATION/DATA/initial_file.txt
