#! bin/bash
cd ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/1_ANNOTATION
ln ~/WEEK2_DAY3_EXERCISE/DATA_REPOSITORY/*.* ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/1_ANNOTATION/DATA
echo "University of Groningen, Ecology and Evolution, "BillieMantzOik"" > ~/WEEK2_DAY3_EXERCISE/GITHUB_TEST/1_ANNOTATION/DATA/initial_file.txt
